ServerName qa.carzonrent.com
ServerTokens Prod
ServerSignature Off
TraceEnable Off

SSLProxyEngine On
Timeout 2400
ProxyTimeout 2400
ProxyBadHeader Ignore
ProxyRequests Off
ProxyPreserveHost On

<VirtualHost *:80>
    ServerName qa.carzonrent.com
    ServerAlias qa.carzonrent localhost

    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Forwarded-Port "8081"

    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "geolocation=(), camera=(), microphone=()"

    ProxyPass        / http://127.0.0.1:8085/ connectiontimeout=5 timeout=2400 retry=0
    ProxyPassReverse / http://127.0.0.1:8085/

    ErrorLog  /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
