{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "carzonrent-qa.fullname" . }}
  namespace: {{ include "carzonrent-qa.namespace" . }}
  labels:
    {{- include "carzonrent-qa.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.quota.hard | nindent 4 }}
{{- end }}
