{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "carzonrent-qa.serviceAccountName" . }}
  namespace: {{ include "carzonrent-qa.namespace" . }}
  labels:
    {{- include "carzonrent-qa.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
