apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: print-quota-ingress
  namespace: print-quota
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qa.carzonrent.com
      secretName: print-quota-tls
  rules:
    - host: qa.carzonrent.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: print-quota-service
                port:
                  number: 80
