apiVersion: v1
kind: Secret
metadata:
  name: carzonrent-qa-secret
  namespace: carzonrent-qa
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "replace-with-qa-db-password"
  SPRING_LDAP_PASSWORD: "replace-with-qa-ldap-password"
